chore: test_wksp_ctl formatting

diff --git a/src/util/wksp/test_wksp_ctl b/src/util/wksp/test_wksp_ctl
--- a/src/util/wksp/test_wksp_ctl
+++ b/src/util/wksp/test_wksp_ctl
@@ -55,8 +55,8 @@ echo Testing new
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT"                         && fail new $?
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT" $PAGE_SZ                && fail new $?
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT" $PAGE_SZ $CPU_IDX       && fail new $?
-"$BIN"/fd_wksp_ctl new bad/name "$PAGE_CNT" $PAGE_SZ $CPU_IDX $MODE && fail new $?
-"$BIN"/fd_wksp_ctl new "$WKSP"    0         $PAGE_SZ $CPU_IDX $MODE && fail new $?
+"$BIN"/fd_wksp_ctl new bad/name   "$PAGE_CNT" $PAGE_SZ $CPU_IDX $MODE && fail new $?
+"$BIN"/fd_wksp_ctl new "$WKSP"    0           $PAGE_SZ $CPU_IDX $MODE && fail new $?
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT" bad_sz   $CPU_IDX $MODE && fail new $?
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT" $PAGE_SZ -1       $MODE && fail new $?
 "$BIN"/fd_wksp_ctl new "$WKSP"    "$PAGE_CNT" $PAGE_SZ $CPU_IDX -1    && fail new $?
@@ -66,11 +66,11 @@ echo Testing new
 echo Testing alloc
 
 "$BIN"/fd_wksp_ctl alloc                                          && fail alloc $?
-"$BIN"/fd_wksp_ctl alloc "$WKSP"                                    && fail alloc $?
-"$BIN"/fd_wksp_ctl alloc "$WKSP"    4096                            && fail alloc $?
+"$BIN"/fd_wksp_ctl alloc "$WKSP"                                  && fail alloc $?
+"$BIN"/fd_wksp_ctl alloc "$WKSP"  4096                            && fail alloc $?
 "$BIN"/fd_wksp_ctl alloc bad/name 4096 2097152                    && fail alloc $?
-"$BIN"/fd_wksp_ctl alloc "$WKSP"    -1   2097152                    && fail alloc $?
-"$BIN"/fd_wksp_ctl alloc "$WKSP"    4096 -1                         && fail alloc $?
+"$BIN"/fd_wksp_ctl alloc "$WKSP"  -1   2097152                    && fail alloc $?
+"$BIN"/fd_wksp_ctl alloc "$WKSP"  4096 -1                         && fail alloc $?
 
 GADDR=$("$BIN"/fd_wksp_ctl alloc "$WKSP" 4096 2097152 || fail alloc $?)
 
@@ -80,32 +80,32 @@ GADDR3=$("$BIN"/fd_wksp_ctl tag 2345 alloc "$WKSP" 4096 4096 || fail alloc $?)
 
 echo Testing memset
 
-"$BIN"/fd_wksp_ctl memset            && fail memset $?
+"$BIN"/fd_wksp_ctl memset              && fail memset $?
 "$BIN"/fd_wksp_ctl memset "$GADDR"     && fail memset $?
-"$BIN"/fd_wksp_ctl memset bad/name 0 || fail memset $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
-"$BIN"/fd_wksp_ctl memset "$GADDR"   0 || fail memset $?
+"$BIN"/fd_wksp_ctl memset bad/name 0   || fail memset $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
+"$BIN"/fd_wksp_ctl memset "$GADDR" 0   || fail memset $?
 
 echo Testing check
 
-"$BIN"/fd_wksp_ctl check          && fail check $?
-"$BIN"/fd_wksp_ctl check bad/name && fail check $?
+"$BIN"/fd_wksp_ctl check            && fail check $?
+"$BIN"/fd_wksp_ctl check bad/name   && fail check $?
 "$BIN"/fd_wksp_ctl check "$WKSP"    || fail check $?
 
 echo Testing usage
 
 "$BIN"/fd_wksp_ctl usage               && fail usage $?
 "$BIN"/fd_wksp_ctl usage bad/name      && fail usage $?
-"$BIN"/fd_wksp_ctl usage bad/name    1 \
-                 usage "$WKSP"       1 \
-                 usage "$WKSP"    1234 \
-                 usage "$WKSP"    2345 \
+"$BIN"/fd_wksp_ctl usage bad/name      1 \
+                   usage "$WKSP"       1 \
+                   usage "$WKSP"    1234 \
+                   usage "$WKSP"    2345 \
 || fail usage $?
 
 echo Testing query
 
 "$BIN"/fd_wksp_ctl query          && fail query $?
 "$BIN"/fd_wksp_ctl query bad/name && fail query $?
-"$BIN"/fd_wksp_ctl query "$WKSP"    || fail query $?
+"$BIN"/fd_wksp_ctl query "$WKSP"  || fail query $?
 
 echo Testing tag-query
 
@@ -119,45 +119,45 @@ echo Testing tag-query
 
 echo Testing tag-free
 
-"$BIN"/fd_wksp_ctl tag-free       && fail tag-free $?
+"$BIN"/fd_wksp_ctl tag-free         && fail tag-free $?
 "$BIN"/fd_wksp_ctl tag-free "$WKSP" && fail tag-free $?
-"$BIN"/fd_wksp_ctl tag-free bad   1234 \
-                 tag-free "$WKSP"    0 \
-                 tag-free "$WKSP" 4096 \
-                 tag-free "$WKSP"    2 \
-                 tag-free "$WKSP" 1234 \
-                 tag-free "$WKSP" 2345 \
-                 tag-free "$WKSP" 1234 \
+"$BIN"/fd_wksp_ctl tag-free bad     1234 \
+                   tag-free "$WKSP"    0 \
+                   tag-free "$WKSP" 4096 \
+                   tag-free "$WKSP"    2 \
+                   tag-free "$WKSP" 1234 \
+                   tag-free "$WKSP" 2345 \
+                   tag-free "$WKSP" 1234 \
 || fail tag-free $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
 
 echo Testing free
 
 "$BIN"/fd_wksp_ctl free          && fail free $?
 "$BIN"/fd_wksp_ctl free bad/name || fail free $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
-"$BIN"/fd_wksp_ctl free "$GADDR"   || fail free $?
-"$BIN"/fd_wksp_ctl free "$GADDR"   || fail free $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
+"$BIN"/fd_wksp_ctl free "$GADDR" || fail free $?
+"$BIN"/fd_wksp_ctl free "$GADDR" || fail free $? # Yes ... a fail here is success from cmd exec POV (fail is logged)
 
 echo Testing reset
 
 "$BIN"/fd_wksp_ctl reset          && fail reset $?
 "$BIN"/fd_wksp_ctl reset bad/name && fail reset $?
-"$BIN"/fd_wksp_ctl reset "$WKSP"    || fail reset $?
+"$BIN"/fd_wksp_ctl reset "$WKSP"  || fail reset $?
 
 echo Testing delete
 
 "$BIN"/fd_wksp_ctl delete          && fail delete $?
 "$BIN"/fd_wksp_ctl delete bad/name && fail delete $?
-"$BIN"/fd_wksp_ctl delete "$WKSP"    || fail delete $?
+"$BIN"/fd_wksp_ctl delete "$WKSP"  || fail delete $?
 
 echo Testing multi
 
-"$BIN"/fd_wksp_ctl new    "$WKSP" "$PAGE_CNT" $PAGE_SZ $CPU_IDX $MODE check "$WKSP" \
-                 query  "$WKSP"                                   check "$WKSP" \
-                 alloc  "$WKSP" 4096 2097152                      check "$WKSP" \
-                 query  "$WKSP"                                   check "$WKSP" \
-                 reset  "$WKSP"                                   check "$WKSP" \
-                 query  "$WKSP"                                   check "$WKSP" \
-                 delete "$WKSP"                                               \
+"$BIN"/fd_wksp_ctl new  "$WKSP" "$PAGE_CNT" $PAGE_SZ $CPU_IDX $MODE check "$WKSP" \
+                 query  "$WKSP"                                     check "$WKSP" \
+                 alloc  "$WKSP" 4096 2097152                        check "$WKSP" \
+                 query  "$WKSP"                                     check "$WKSP" \
+                 reset  "$WKSP"                                     check "$WKSP" \
+                 query  "$WKSP"                                     check "$WKSP" \
+                 delete "$WKSP"                                                   \
 || fail multi $?
 
 echo pass
